/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 69
#line 1 "n1ql.leg"

#include "n1ql_parser.h"

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_DIGIT(yycontext *yy); /* 69 */
YY_RULE(int) yy_STRING_LITERAL(yycontext *yy); /* 68 */
YY_RULE(int) yy_BOOLEAN_LITERAL(yycontext *yy); /* 67 */
YY_RULE(int) yy_NUMERIC_LITERAL(yycontext *yy); /* 66 */
YY_RULE(int) yy_SATISFIES(yycontext *yy); /* 65 */
YY_RULE(int) yy_REGEX(yycontext *yy); /* 64 */
YY_RULE(int) yy_OR(yycontext *yy); /* 63 */
YY_RULE(int) yy_NOT(yycontext *yy); /* 62 */
YY_RULE(int) yy_MATCH(yycontext *yy); /* 61 */
YY_RULE(int) yy_LIKE(yycontext *yy); /* 60 */
YY_RULE(int) yy_IS(yycontext *yy); /* 59 */
YY_RULE(int) yy_IN(yycontext *yy); /* 58 */
YY_RULE(int) yy_BETWEEN(yycontext *yy); /* 57 */
YY_RULE(int) yy_variableName(yycontext *yy); /* 56 */
YY_RULE(int) yy_AND(yycontext *yy); /* 55 */
YY_RULE(int) yy_EVERY(yycontext *yy); /* 54 */
YY_RULE(int) yy_ANY(yycontext *yy); /* 53 */
YY_RULE(int) yy_anyEvery(yycontext *yy); /* 52 */
YY_RULE(int) yy_functionName(yycontext *yy); /* 51 */
YY_RULE(int) yy_function(yycontext *yy); /* 50 */
YY_RULE(int) yy_propertyName(yycontext *yy); /* 49 */
YY_RULE(int) yy_META(yycontext *yy); /* 48 */
YY_RULE(int) yy_meta(yycontext *yy); /* 47 */
YY_RULE(int) yy_literal(yycontext *yy); /* 46 */
YY_RULE(int) yy_property(yycontext *yy); /* 45 */
YY_RULE(int) yy_OFFSET(yycontext *yy); /* 44 */
YY_RULE(int) yy_offset(yycontext *yy); /* 43 */
YY_RULE(int) yy_LIMIT(yycontext *yy); /* 42 */
YY_RULE(int) yy_DESC(yycontext *yy); /* 41 */
YY_RULE(int) yy_ASC(yycontext *yy); /* 40 */
YY_RULE(int) yy_order(yycontext *yy); /* 39 */
YY_RULE(int) yy_ordering(yycontext *yy); /* 38 */
YY_RULE(int) yy_ORDER(yycontext *yy); /* 37 */
YY_RULE(int) yy_HAVING(yycontext *yy); /* 36 */
YY_RULE(int) yy_having(yycontext *yy); /* 35 */
YY_RULE(int) yy_BY(yycontext *yy); /* 34 */
YY_RULE(int) yy_GROUP(yycontext *yy); /* 33 */
YY_RULE(int) yy_WHERE(yycontext *yy); /* 32 */
YY_RULE(int) yy_ON(yycontext *yy); /* 31 */
YY_RULE(int) yy_JOIN(yycontext *yy); /* 30 */
YY_RULE(int) yy_CROSS(yycontext *yy); /* 29 */
YY_RULE(int) yy_INNER(yycontext *yy); /* 28 */
YY_RULE(int) yy_OUTER(yycontext *yy); /* 27 */
YY_RULE(int) yy_LEFT(yycontext *yy); /* 26 */
YY_RULE(int) yy_joinConstraint(yycontext *yy); /* 25 */
YY_RULE(int) yy_joinOperator(yycontext *yy); /* 24 */
YY_RULE(int) yy_joins(yycontext *yy); /* 23 */
YY_RULE(int) yy_dataSource(yycontext *yy); /* 22 */
YY_RULE(int) yy_FROM(yycontext *yy); /* 21 */
YY_RULE(int) yy_databaseAlias(yycontext *yy); /* 20 */
YY_RULE(int) yy_databaseName(yycontext *yy); /* 19 */
YY_RULE(int) yy_IDENTIFIER(yycontext *yy); /* 18 */
YY_RULE(int) yy_expression(yycontext *yy); /* 17 */
YY_RULE(int) yy_columnAlias(yycontext *yy); /* 16 */
YY_RULE(int) yy___(yycontext *yy); /* 15 */
YY_RULE(int) yy_AS(yycontext *yy); /* 14 */
YY_RULE(int) yy_dataSourceName(yycontext *yy); /* 13 */
YY_RULE(int) yy_selectResult(yycontext *yy); /* 12 */
YY_RULE(int) yy_DISTINCT(yycontext *yy); /* 11 */
YY_RULE(int) yy_SELECT(yycontext *yy); /* 10 */
YY_RULE(int) yy_limit(yycontext *yy); /* 9 */
YY_RULE(int) yy_orderBy(yycontext *yy); /* 8 */
YY_RULE(int) yy_groupBy(yycontext *yy); /* 7 */
YY_RULE(int) yy_where(yycontext *yy); /* 6 */
YY_RULE(int) yy_from(yycontext *yy); /* 5 */
YY_RULE(int) yy_select(yycontext *yy); /* 4 */
YY_RULE(int) yy_selectStatement(yycontext *yy); /* 3 */
YY_RULE(int) yy__(yycontext *yy); /* 2 */
YY_RULE(int) yy_n1ql(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_IDENTIFIER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IDENTIFIER\n"));
  {
#line 103
   printf("IDENTIFIER: %s\n", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_propertyName(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_propertyName\n"));
  {
#line 98
   printf("PROPERTYNAME: %s\n", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_property(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_property\n"));
  {
#line 89
   printf("PROPERTY: %s\n", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_n1ql(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_n1ql\n"));
  {
#line 6
  sN1QLResult = s;;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}

YY_RULE(int) yy_DIGIT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DIGIT"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "DIGIT", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DIGIT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRING_LITERAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRING_LITERAL"));  if (!yymatchChar(yy, '\'')) goto l2;
  l3:;	
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;  if (!yymatchChar(yy, '\'')) goto l7;  goto l6;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }  goto l5;
  l6:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;  if (!yymatchString(yy, "''")) goto l4;
  }
  l5:;	  goto l3;
  l4:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;
  }  if (!yymatchChar(yy, '\'')) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "STRING_LITERAL", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRING_LITERAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BOOLEAN_LITERAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BOOLEAN_LITERAL"));
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;  if (!yymatchString(yy, "TRUE")) goto l10;  goto l9;
  l10:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;  if (!yymatchString(yy, "FALSE")) goto l8;
  }
  l9:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "BOOLEAN_LITERAL", yy->__buf+yy->__pos));
  return 1;
  l8:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BOOLEAN_LITERAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMERIC_LITERAL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMERIC_LITERAL"));
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;
  {  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l14;  goto l15;
  l14:;	  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  }
  l15:;	  if (!yy_DIGIT(yy)) goto l13;
  l16:;	
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yy_DIGIT(yy)) goto l17;  goto l16;
  l17:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l18;
  l20:;	
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yy_DIGIT(yy)) goto l21;  goto l20;
  l21:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;
  }  goto l19;
  l18:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;
  }
  l19:;	
  {  int yypos22= yy->__pos, yythunkpos22= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\040\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l22;
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;  goto l25;
  l24:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  }
  l25:;	  if (!yy_DIGIT(yy)) goto l22;
  l26:;	
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yy_DIGIT(yy)) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;
  }  goto l23;
  l22:;	  yy->__pos= yypos22; yy->__thunkpos= yythunkpos22;
  }
  l23:;	  goto l12;
  l13:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  {  int yypos28= yy->__pos, yythunkpos28= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l28;  goto l29;
  l28:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;
  }
  l29:;	  if (!yymatchChar(yy, '.')) goto l11;  if (!yy_DIGIT(yy)) goto l11;
  l30:;	
  {  int yypos31= yy->__pos, yythunkpos31= yy->__thunkpos;  if (!yy_DIGIT(yy)) goto l31;  goto l30;
  l31:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;
  }
  {  int yypos32= yy->__pos, yythunkpos32= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\040\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;
  {  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l34;  goto l35;
  l34:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;
  }
  l35:;	  if (!yy_DIGIT(yy)) goto l32;
  l36:;	
  {  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;  if (!yy_DIGIT(yy)) goto l37;  goto l36;
  l37:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;
  }  goto l33;
  l32:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;
  }
  l33:;	
  }
  l12:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMERIC_LITERAL", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMERIC_LITERAL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SATISFIES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SATISFIES"));  if (!yymatchString(yy, "SATISFIES")) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "SATISFIES", yy->__buf+yy->__pos));
  return 1;
  l38:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SATISFIES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_REGEX(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "REGEX"));  if (!yymatchString(yy, "REGEX")) goto l39;
  yyprintf((stderr, "  ok   %s @ %s\n", "REGEX", yy->__buf+yy->__pos));
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "REGEX", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OR"));  if (!yymatchString(yy, "OR")) goto l40;
  yyprintf((stderr, "  ok   %s @ %s\n", "OR", yy->__buf+yy->__pos));
  return 1;
  l40:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NOT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NOT"));  if (!yymatchString(yy, "NOT")) goto l41;
  yyprintf((stderr, "  ok   %s @ %s\n", "NOT", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MATCH(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MATCH"));  if (!yymatchString(yy, "MATCH")) goto l42;
  yyprintf((stderr, "  ok   %s @ %s\n", "MATCH", yy->__buf+yy->__pos));
  return 1;
  l42:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MATCH", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LIKE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LIKE"));  if (!yymatchString(yy, "LIKE")) goto l43;
  yyprintf((stderr, "  ok   %s @ %s\n", "LIKE", yy->__buf+yy->__pos));
  return 1;
  l43:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LIKE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IS"));  if (!yymatchString(yy, "IS")) goto l44;
  yyprintf((stderr, "  ok   %s @ %s\n", "IS", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IN"));  if (!yymatchString(yy, "IN")) goto l45;
  yyprintf((stderr, "  ok   %s @ %s\n", "IN", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BETWEEN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BETWEEN"));  if (!yymatchString(yy, "BETWEEN")) goto l46;
  yyprintf((stderr, "  ok   %s @ %s\n", "BETWEEN", yy->__buf+yy->__pos));
  return 1;
  l46:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BETWEEN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_variableName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "variableName"));  if (!yy_IDENTIFIER(yy)) goto l47;
  yyprintf((stderr, "  ok   %s @ %s\n", "variableName", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "variableName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_AND(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "AND"));  if (!yymatchString(yy, "AND")) goto l48;
  yyprintf((stderr, "  ok   %s @ %s\n", "AND", yy->__buf+yy->__pos));
  return 1;
  l48:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AND", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EVERY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EVERY"));  if (!yymatchString(yy, "EVERY")) goto l49;
  yyprintf((stderr, "  ok   %s @ %s\n", "EVERY", yy->__buf+yy->__pos));
  return 1;
  l49:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EVERY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ANY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ANY"));  if (!yymatchString(yy, "ANY")) goto l50;
  yyprintf((stderr, "  ok   %s @ %s\n", "ANY", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ANY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_anyEvery(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "anyEvery"));
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yy_ANY(yy)) goto l53;  goto l52;
  l53:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  if (!yy_EVERY(yy)) goto l54;  goto l52;
  l54:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  if (!yy_ANY(yy)) goto l51;  if (!yy___(yy)) goto l51;  if (!yy_AND(yy)) goto l51;  if (!yy___(yy)) goto l51;  if (!yy_EVERY(yy)) goto l51;
  }
  l52:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "anyEvery", yy->__buf+yy->__pos));
  return 1;
  l51:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anyEvery", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_functionName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "functionName"));  if (!yy_IDENTIFIER(yy)) goto l55;
  yyprintf((stderr, "  ok   %s @ %s\n", "functionName", yy->__buf+yy->__pos));
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "functionName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_function(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "function"));  if (!yy_functionName(yy)) goto l56;  if (!yymatchChar(yy, '(')) goto l56;
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;  if (!yy_expression(yy)) goto l57;
  l59:;	
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l60;  if (!yy_expression(yy)) goto l60;  goto l59;
  l60:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;
  }  goto l58;
  l57:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;
  }
  l58:;	  if (!yymatchChar(yy, ')')) goto l56;
  yyprintf((stderr, "  ok   %s @ %s\n", "function", yy->__buf+yy->__pos));
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "function", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_propertyName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "propertyName"));  if (!yy_IDENTIFIER(yy)) goto l61;  yyDo(yy, yy_1_propertyName, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "propertyName", yy->__buf+yy->__pos));
  return 1;
  l61:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "propertyName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_META(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "META"));  if (!yymatchString(yy, "META")) goto l62;
  yyprintf((stderr, "  ok   %s @ %s\n", "META", yy->__buf+yy->__pos));
  return 1;
  l62:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "META", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_meta(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "meta"));
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yy_dataSourceName(yy)) goto l64;  if (!yy__(yy)) goto l64;  if (!yymatchChar(yy, '.')) goto l64;  if (!yy__(yy)) goto l64;  goto l65;
  l64:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;
  }
  l65:;	  if (!yy_META(yy)) goto l63;  if (!yy__(yy)) goto l63;  if (!yymatchChar(yy, '.')) goto l63;  if (!yy__(yy)) goto l63;  if (!yy_propertyName(yy)) goto l63;
  yyprintf((stderr, "  ok   %s @ %s\n", "meta", yy->__buf+yy->__pos));
  return 1;
  l63:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "meta", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_literal(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "literal"));
  {  int yypos67= yy->__pos, yythunkpos67= yy->__thunkpos;  if (!yy_NUMERIC_LITERAL(yy)) goto l68;  goto l67;
  l68:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_BOOLEAN_LITERAL(yy)) goto l69;  goto l67;
  l69:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_STRING_LITERAL(yy)) goto l70;  goto l67;
  l70:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yymatchString(yy, "NULL")) goto l71;  goto l67;
  l71:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yymatchString(yy, "MISSING")) goto l66;
  }
  l67:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "literal", yy->__buf+yy->__pos));
  return 1;
  l66:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "literal", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_property(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "property"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l72;
#undef yytext
#undef yyleng
  }
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yy_dataSourceName(yy)) goto l73;  if (!yy__(yy)) goto l73;  if (!yymatchChar(yy, '.')) goto l73;  if (!yy__(yy)) goto l73;  goto l74;
  l73:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;
  }
  l74:;	  if (!yy_propertyName(yy)) goto l72;
  l75:;	
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yy__(yy)) goto l76;  if (!yymatchChar(yy, '.')) goto l76;  if (!yy__(yy)) goto l76;  if (!yy_propertyName(yy)) goto l76;  goto l75;
  l76:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l72;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_property, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "property", yy->__buf+yy->__pos));
  return 1;
  l72:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "property", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OFFSET(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OFFSET"));  if (!yymatchString(yy, "OFFSET")) goto l77;
  yyprintf((stderr, "  ok   %s @ %s\n", "OFFSET", yy->__buf+yy->__pos));
  return 1;
  l77:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OFFSET", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_offset(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "offset"));  if (!yy_OFFSET(yy)) goto l78;  if (!yy__(yy)) goto l78;  if (!yy_expression(yy)) goto l78;
  yyprintf((stderr, "  ok   %s @ %s\n", "offset", yy->__buf+yy->__pos));
  return 1;
  l78:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "offset", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LIMIT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LIMIT"));  if (!yymatchString(yy, "LIMIT")) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "LIMIT", yy->__buf+yy->__pos));
  return 1;
  l79:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LIMIT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DESC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DESC"));  if (!yymatchString(yy, "DESC")) goto l80;
  yyprintf((stderr, "  ok   %s @ %s\n", "DESC", yy->__buf+yy->__pos));
  return 1;
  l80:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DESC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ASC(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ASC"));  if (!yymatchString(yy, "ASC")) goto l81;
  yyprintf((stderr, "  ok   %s @ %s\n", "ASC", yy->__buf+yy->__pos));
  return 1;
  l81:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ASC", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_order(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "order"));
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_ASC(yy)) goto l84;  goto l83;
  l84:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;  if (!yy_DESC(yy)) goto l82;
  }
  l83:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "order", yy->__buf+yy->__pos));
  return 1;
  l82:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "order", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ordering(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ordering"));  if (!yy_expression(yy)) goto l85;
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;  if (!yy__(yy)) goto l86;  if (!yy_order(yy)) goto l86;  goto l87;
  l86:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;
  }
  l87:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ordering", yy->__buf+yy->__pos));
  return 1;
  l85:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ordering", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ORDER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ORDER"));  if (!yymatchString(yy, "ORDER")) goto l88;
  yyprintf((stderr, "  ok   %s @ %s\n", "ORDER", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ORDER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_HAVING(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "HAVING"));  if (!yymatchString(yy, "HAVING")) goto l89;
  yyprintf((stderr, "  ok   %s @ %s\n", "HAVING", yy->__buf+yy->__pos));
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HAVING", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_having(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "having"));  if (!yy_HAVING(yy)) goto l90;  if (!yy__(yy)) goto l90;  if (!yy_expression(yy)) goto l90;
  yyprintf((stderr, "  ok   %s @ %s\n", "having", yy->__buf+yy->__pos));
  return 1;
  l90:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "having", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_BY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "BY"));  if (!yymatchString(yy, "BY")) goto l91;
  yyprintf((stderr, "  ok   %s @ %s\n", "BY", yy->__buf+yy->__pos));
  return 1;
  l91:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_GROUP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "GROUP"));  if (!yymatchString(yy, "GROUP")) goto l92;
  yyprintf((stderr, "  ok   %s @ %s\n", "GROUP", yy->__buf+yy->__pos));
  return 1;
  l92:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GROUP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_WHERE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "WHERE"));  if (!yymatchString(yy, "WHERE")) goto l93;
  yyprintf((stderr, "  ok   %s @ %s\n", "WHERE", yy->__buf+yy->__pos));
  return 1;
  l93:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "WHERE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ON(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ON"));  if (!yymatchString(yy, "ON")) goto l94;
  yyprintf((stderr, "  ok   %s @ %s\n", "ON", yy->__buf+yy->__pos));
  return 1;
  l94:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ON", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_JOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "JOIN"));  if (!yymatchString(yy, "JOIN")) goto l95;
  yyprintf((stderr, "  ok   %s @ %s\n", "JOIN", yy->__buf+yy->__pos));
  return 1;
  l95:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "JOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CROSS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CROSS"));  if (!yymatchString(yy, "CROSS")) goto l96;
  yyprintf((stderr, "  ok   %s @ %s\n", "CROSS", yy->__buf+yy->__pos));
  return 1;
  l96:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CROSS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_INNER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "INNER"));  if (!yymatchString(yy, "INNER")) goto l97;
  yyprintf((stderr, "  ok   %s @ %s\n", "INNER", yy->__buf+yy->__pos));
  return 1;
  l97:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INNER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OUTER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OUTER"));  if (!yymatchString(yy, "OUTER")) goto l98;
  yyprintf((stderr, "  ok   %s @ %s\n", "OUTER", yy->__buf+yy->__pos));
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OUTER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LEFT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LEFT"));  if (!yymatchString(yy, "LEFT")) goto l99;
  yyprintf((stderr, "  ok   %s @ %s\n", "LEFT", yy->__buf+yy->__pos));
  return 1;
  l99:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LEFT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_joinConstraint(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "joinConstraint"));
  {  int yypos101= yy->__pos, yythunkpos101= yy->__thunkpos;  if (!yy_ON(yy)) goto l101;  if (!yy__(yy)) goto l101;  if (!yy_expression(yy)) goto l101;  goto l102;
  l101:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;
  }
  l102:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "joinConstraint", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_joinOperator(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "joinOperator"));
  {  int yypos104= yy->__pos, yythunkpos104= yy->__thunkpos;
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy_LEFT(yy)) goto l107;
  {  int yypos108= yy->__pos, yythunkpos108= yy->__thunkpos;  if (!yy___(yy)) goto l108;  if (!yy_OUTER(yy)) goto l108;  goto l109;
  l108:;	  yy->__pos= yypos108; yy->__thunkpos= yythunkpos108;
  }
  l109:;	  if (!yy___(yy)) goto l107;  goto l106;
  l107:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yy_INNER(yy)) goto l110;  if (!yy___(yy)) goto l110;  goto l106;
  l110:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;  if (!yy_CROSS(yy)) goto l104;  if (!yy___(yy)) goto l104;
  }
  l106:;	  goto l105;
  l104:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;
  }
  l105:;	  if (!yy_JOIN(yy)) goto l103;
  yyprintf((stderr, "  ok   %s @ %s\n", "joinOperator", yy->__buf+yy->__pos));
  return 1;
  l103:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "joinOperator", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_joins(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "joins"));  if (!yy_dataSource(yy)) goto l111;
  l112:;	
  {  int yypos113= yy->__pos, yythunkpos113= yy->__thunkpos;  if (!yy_joinOperator(yy)) goto l113;  if (!yy__(yy)) goto l113;  if (!yy_dataSource(yy)) goto l113;  if (!yy__(yy)) goto l113;  if (!yy_joinConstraint(yy)) goto l113;  goto l112;
  l113:;	  yy->__pos= yypos113; yy->__thunkpos= yythunkpos113;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "joins", yy->__buf+yy->__pos));
  return 1;
  l111:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "joins", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_dataSource(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "dataSource"));  if (!yy_databaseName(yy)) goto l114;
  {  int yypos115= yy->__pos, yythunkpos115= yy->__thunkpos;  if (!yy__(yy)) goto l115;  if (!yy_AS(yy)) goto l115;  if (!yy___(yy)) goto l115;  if (!yy_databaseAlias(yy)) goto l115;  goto l116;
  l115:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;
  }
  l116:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "dataSource", yy->__buf+yy->__pos));
  return 1;
  l114:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dataSource", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FROM(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FROM"));  if (!yymatchString(yy, "FROM")) goto l117;
  yyprintf((stderr, "  ok   %s @ %s\n", "FROM", yy->__buf+yy->__pos));
  return 1;
  l117:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FROM", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_databaseAlias(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "databaseAlias"));  if (!yy_IDENTIFIER(yy)) goto l118;
  yyprintf((stderr, "  ok   %s @ %s\n", "databaseAlias", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "databaseAlias", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_databaseName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "databaseName"));  if (!yy_IDENTIFIER(yy)) goto l119;
  yyprintf((stderr, "  ok   %s @ %s\n", "databaseName", yy->__buf+yy->__pos));
  return 1;
  l119:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "databaseName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IDENTIFIER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IDENTIFIER"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l120;
  l121:;	
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l122;  goto l121;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }  yyDo(yy, yy_1_IDENTIFIER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENTIFIER", yy->__buf+yy->__pos));
  return 1;
  l120:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENTIFIER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_expression(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "expression"));
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yymatchChar(yy, '(')) goto l125;  if (!yy_expression(yy)) goto l125;  if (!yymatchChar(yy, ')')) goto l125;  goto l124;
  l125:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;  if (!yy_property(yy)) goto l126;  goto l124;
  l126:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;  if (!yy_literal(yy)) goto l123;
  }
  l124:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", yy->__buf+yy->__pos));
  return 1;
  l123:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_columnAlias(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "columnAlias"));  if (!yy_IDENTIFIER(yy)) goto l127;
  yyprintf((stderr, "  ok   %s @ %s\n", "columnAlias", yy->__buf+yy->__pos));
  return 1;
  l127:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "columnAlias", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy___(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "__"));  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l128;
  l129:;	
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l130;  goto l129;
  l130:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 1;
  l128:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_AS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "AS"));  if (!yymatchString(yy, "AS")) goto l131;
  yyprintf((stderr, "  ok   %s @ %s\n", "AS", yy->__buf+yy->__pos));
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_dataSourceName(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "dataSourceName"));  if (!yy_IDENTIFIER(yy)) goto l132;
  yyprintf((stderr, "  ok   %s @ %s\n", "dataSourceName", yy->__buf+yy->__pos));
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dataSourceName", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_selectResult(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "selectResult"));
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;  if (!yy_dataSourceName(yy)) goto l136;  if (!yy__(yy)) goto l136;  if (!yymatchChar(yy, '.')) goto l136;  if (!yy__(yy)) goto l136;  goto l137;
  l136:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;
  }
  l137:;	  if (!yymatchChar(yy, '*')) goto l135;
  {  int yypos138= yy->__pos, yythunkpos138= yy->__thunkpos;  if (!yy__(yy)) goto l138;  if (!yy_AS(yy)) goto l138;  if (!yy___(yy)) goto l138;  if (!yy_columnAlias(yy)) goto l138;  goto l139;
  l138:;	  yy->__pos= yypos138; yy->__thunkpos= yythunkpos138;
  }
  l139:;	  goto l134;
  l135:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;  if (!yy_expression(yy)) goto l133;
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yy__(yy)) goto l140;  if (!yy_AS(yy)) goto l140;  if (!yy___(yy)) goto l140;  if (!yy_columnAlias(yy)) goto l140;  goto l141;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }
  l141:;	
  }
  l134:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "selectResult", yy->__buf+yy->__pos));
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "selectResult", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DISTINCT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DISTINCT"));  if (!yymatchString(yy, "DISTINCT")) goto l142;
  yyprintf((stderr, "  ok   %s @ %s\n", "DISTINCT", yy->__buf+yy->__pos));
  return 1;
  l142:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DISTINCT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SELECT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SELECT"));  if (!yymatchString(yy, "SELECT")) goto l143;
  yyprintf((stderr, "  ok   %s @ %s\n", "SELECT", yy->__buf+yy->__pos));
  return 1;
  l143:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SELECT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_limit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "limit"));  if (!yy_LIMIT(yy)) goto l144;  if (!yy___(yy)) goto l144;  if (!yy_expression(yy)) goto l144;
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yy__(yy)) goto l145;  if (!yy_offset(yy)) goto l145;  goto l146;
  l145:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;
  }
  l146:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "limit", yy->__buf+yy->__pos));
  return 1;
  l144:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "limit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_orderBy(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "orderBy"));  if (!yy_ORDER(yy)) goto l147;  if (!yy__(yy)) goto l147;  if (!yy_BY(yy)) goto l147;  if (!yy__(yy)) goto l147;  if (!yy_ordering(yy)) goto l147;
  l148:;	
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yy__(yy)) goto l149;  if (!yymatchChar(yy, ',')) goto l149;  if (!yy__(yy)) goto l149;  if (!yy_ordering(yy)) goto l149;  goto l148;
  l149:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "orderBy", yy->__buf+yy->__pos));
  return 1;
  l147:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "orderBy", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_groupBy(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "groupBy"));  if (!yy_GROUP(yy)) goto l150;  if (!yy__(yy)) goto l150;  if (!yy_BY(yy)) goto l150;  if (!yy__(yy)) goto l150;  if (!yy_expression(yy)) goto l150;
  l151:;	
  {  int yypos152= yy->__pos, yythunkpos152= yy->__thunkpos;  if (!yy__(yy)) goto l152;  if (!yymatchChar(yy, ',')) goto l152;  if (!yy__(yy)) goto l152;  if (!yy_expression(yy)) goto l152;  goto l151;
  l152:;	  yy->__pos= yypos152; yy->__thunkpos= yythunkpos152;
  }
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;  if (!yy__(yy)) goto l153;  if (!yy_having(yy)) goto l153;  goto l154;
  l153:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;
  }
  l154:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "groupBy", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "groupBy", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_where(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "where"));  if (!yy_WHERE(yy)) goto l155;  if (!yy__(yy)) goto l155;  if (!yy_expression(yy)) goto l155;
  yyprintf((stderr, "  ok   %s @ %s\n", "where", yy->__buf+yy->__pos));
  return 1;
  l155:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "where", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_from(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "from"));  if (!yy_FROM(yy)) goto l156;  if (!yy___(yy)) goto l156;
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_dataSource(yy)) goto l158;  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_joins(yy)) goto l156;
  }
  l157:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "from", yy->__buf+yy->__pos));
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "from", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_select(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "select"));  if (!yy_SELECT(yy)) goto l159;  if (!yy__(yy)) goto l159;
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_DISTINCT(yy)) goto l160;  if (!yy__(yy)) goto l160;  goto l161;
  l160:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;
  }
  l161:;	  if (!yy_selectResult(yy)) goto l159;
  l162:;	
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy__(yy)) goto l163;  if (!yymatchChar(yy, ',')) goto l163;  if (!yy__(yy)) goto l163;  if (!yy_selectResult(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "select", yy->__buf+yy->__pos));
  return 1;
  l159:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "select", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_selectStatement(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "selectStatement"));  if (!yy_select(yy)) goto l164;
  {  int yypos165= yy->__pos, yythunkpos165= yy->__thunkpos;  if (!yy__(yy)) goto l165;  if (!yy_from(yy)) goto l165;  goto l166;
  l165:;	  yy->__pos= yypos165; yy->__thunkpos= yythunkpos165;
  }
  l166:;	
  {  int yypos167= yy->__pos, yythunkpos167= yy->__thunkpos;  if (!yy__(yy)) goto l167;  if (!yy_where(yy)) goto l167;  goto l168;
  l167:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;
  }
  l168:;	
  {  int yypos169= yy->__pos, yythunkpos169= yy->__thunkpos;  if (!yy__(yy)) goto l169;  if (!yy_groupBy(yy)) goto l169;  goto l170;
  l169:;	  yy->__pos= yypos169; yy->__thunkpos= yythunkpos169;
  }
  l170:;	
  {  int yypos171= yy->__pos, yythunkpos171= yy->__thunkpos;  if (!yy__(yy)) goto l171;  if (!yy_orderBy(yy)) goto l171;  goto l172;
  l171:;	  yy->__pos= yypos171; yy->__thunkpos= yythunkpos171;
  }
  l172:;	
  {  int yypos173= yy->__pos, yythunkpos173= yy->__thunkpos;  if (!yy__(yy)) goto l173;  if (!yy_limit(yy)) goto l173;  goto l174;
  l173:;	  yy->__pos= yypos173; yy->__thunkpos= yythunkpos173;
  }
  l174:;	
  {  int yypos175= yy->__pos, yythunkpos175= yy->__thunkpos;  if (!yy__(yy)) goto l175;  if (!yymatchChar(yy, ';')) goto l175;  goto l176;
  l175:;	  yy->__pos= yypos175; yy->__thunkpos= yythunkpos175;
  }
  l176:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "selectStatement", yy->__buf+yy->__pos));
  return 1;
  l164:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "selectStatement", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l178:;	
  {  int yypos179= yy->__pos, yythunkpos179= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l179;  goto l178;
  l179:;	  yy->__pos= yypos179; yy->__thunkpos= yythunkpos179;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_n1ql(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "n1ql"));  if (!yy__(yy)) goto l180;  if (!yy_selectStatement(yy)) goto l180;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l180;
  {  int yypos181= yy->__pos, yythunkpos181= yy->__thunkpos;  if (!yymatchDot(yy)) goto l181;  goto l180;
  l181:;	  yy->__pos= yypos181; yy->__thunkpos= yythunkpos181;
  }  yyDo(yy, yy_1_n1ql, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "n1ql", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l180:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "n1ql", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_n1ql);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
