#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Copyright (c) 2022 Couchbase, Inc All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from datetime import datetime, timedelta
from typing import cast
from defs import DefaultGenerator, DefaultEntry, Constant, ConstantValue, ConstantType

top_level_format = """//
// Copyright (c) {year}-present Couchbase, Inc All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// THIS IS AN AUTOGENERATED FILE, MANUAL CHANGES SHOULD BE EXPECTED TO
// BE OVERWRITTEN

package com.couchbase.lite;
public final class Defaults {{
\tprivate Defaults() {{}}

{generated}}}
"""

class JavaDefaultGenerator(DefaultGenerator):
    _type_mapping: dict[str, str] = {
        ConstantType.UINT_TYPE_ID: "int",
        ConstantType.TIMESPAN_TYPE_ID: "int"
    }

    def __init__(self, input: list[DefaultEntry]):
        super().__init__(input)

    def transform_var_name(self, name: str) -> str:
        return "".join(["_" + c.upper() if c.isupper() else c.upper() for c in name]).lstrip("_")

    def transform_var_value(self, type: ConstantType, value: ConstantValue) -> str:
        if type.subset == "enum":
            enum_val = self.transform_var_name(value.val)
            return f"{type.id}.{enum_val}"

        if type.id == ConstantType.BOOLEAN_TYPE_ID:
            return str(value.val).lower()

        if type.id == ConstantType.TIMESPAN_TYPE_ID:
            if value.unit == "seconds":
                return str(cast(timedelta, value.val).seconds)
            else:
                raise Exception(f"Unknown unit '{value.unit}'")

        if type.id == ConstantType.UINT_TYPE_ID:
            if value.val == -1:
                return "Integer.MAX_INT"

        return str(value)

    def compute_class(self, name: str) -> str:
        return f"\tpublic static final class {name} {{\n\t\tprivate {name}() {{}}\n\n"

    def compute_value(self, constant: Constant) -> str:
        ret_val = f"\t\t// {constant.description}\n"
        type = self._type_mapping[constant.type.id] if constant.type.id in self._type_mapping else constant.type
        name = self.transform_var_name(constant.name)
        value = self.transform_var_value(constant.type, constant.value)
        ret_val += f"\t\tpublic static final {type} {name} = {value};\n\n"
        return ret_val

    def generate(self) -> dict[str, str]:
        output: str = ""
        generated: dict[str, str] = {}
        for entry in self._input:
            output += self.compute_class(entry.name)
            for c in entry.constants:
                if len(c.only_on) > 0 and not "java" in c.only_on:
                    continue
                
                output += self.compute_value(c)
            
            output = output.rstrip() + "\n\t}\n\n"

        output = output.rstrip() + "\n"
        generated["Defaults.java"] = top_level_format.format(year = datetime.now().year, generated = output)
        return generated

if __name__ == "__main__":
    raise Exception("This script is not standalone, it is used with gen_defaults.py")